import type { Metadata } from "next";
import { Aboreto, Monoton, Ruda } from "next/font/google";
import "./globals.css";

// Rename the variable to reflect the correct font name
const aboreto = Ruda({
  weight: "400", // Optional: Specify the font weight
  subsets: ["latin"], // Optional: Specify the subset
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      {/* Apply the font to the body */}
      <body className={aboreto.className}>{children}</body>
    </html>
  );
}
